.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. outbit_qt test_outbit_qt
clean: FORCE
	$(MAKE) -C .. outbit_qt_clean test_outbit_qt_clean
check: FORCE
	$(MAKE) -C .. test_outbit_qt_check
outbit-qt outbit-qt.exe: FORCE
	 $(MAKE) -C .. outbit_qt
